project_id = "ekihgsdoscvgbgqhazru"

[functions.generate-meal-suggestions]
verify_jwt = true

[functions.create-household]
verify_jwt = true

[functions.regenerate-meals]
verify_jwt = true

[functions.dev-reset-account]
verify_jwt = true

[functions.ai-pantry-import]
verify_jwt = true

[functions.generate-shopping-list]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.generate-daily-plan]
verify_jwt = true

[functions.parse-task-input]
verify_jwt = true

